services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "/opt/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "npm run dev -- --host"
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/app
          action: sync
          target: /frontend/app
          ignore:
            - node_modules
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    depends_on:
      - backend